import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Providers from "./components/provider";
import "@rainbow-me/rainbowkit/styles.css";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "EVM-dex | swap | liquidity | vault",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
          <ToastContainer
            position="bottom-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            rtl={false}
            draggable
            theme="dark"
          />
        </Providers>
        
        {/* <div className="relative h-screen">
          <div
            className="absolute bottom-0 right-0 w-auto h-[60px]"
            style={{ aspectRatio: "708 / 234" }}
          >
            <img
              src={`/img/cronosproject.webp`}
              alt="Image"
              className="object-contain w-full h-full"
            />
          </div>
        </div> */}
        
      </body>
    </html>
  );
}
